#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 08, 2018 09:42:28 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import project_movie_slicer4_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.tk.call('encoding', 'system', 'utf-8')
    project_movie_slicer4_support.set_Tk_var()
    top = Wordslicer (root)
    project_movie_slicer4_support.init(root, top)
    root.mainloop()

w = None
def create_Wordslicer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    project_movie_slicer4_support.set_Tk_var()
    top = Wordslicer (w)
    project_movie_slicer4_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Wordslicer():
    global w
    w.destroy()
    w = None


class Wordslicer:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans Mono} -size 12 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("853x687+344+177")
        top.title("Wordslicer")
        top.configure(highlightcolor="black")



        self.images = (

         PhotoImage("img_close", data='''R0lGODlhDAAMAIQUADIyMjc3Nzk5OT09PT
                 8/P0JCQkVFRU1NTU5OTlFRUVZWVmBgYGF hYWlpaXt7e6CgoLm5ucLCwszMzNbW
                 1v//////////////////////////////////// ///////////yH5BAEKAB8ALA
                 AAAAAMAAwAAAUt4CeOZGmaA5mSyQCIwhCUSwEIxHHW+ fkxBgPiBDwshCWHQfc5
                 KkoNUtRHpYYAADs= '''),

         PhotoImage("img_closeactive", data='''R0lGODlhDAAMAIQcALwuEtIzFL46
                 INY0Fdk2FsQ8IdhAI9pAIttCJNlKLtpLL9pMMMNTP cVTPdpZQOBbQd60rN+1rf
                 Czp+zLxPbMxPLX0vHY0/fY0/rm4vvx8Pvy8fzy8P//////// ///////yH5BAEK
                 AB8ALAAAAAAMAAwAAAVHYLQQZEkukWKuxEgg1EPCcilx24NcHGYWFhx P0zANBE
                 GOhhFYGSocTsax2imDOdNtiez9JszjpEg4EAaA5jlNUEASLFICEgIAOw== '''),

         PhotoImage("img_closepressed", data='''R0lGODlhDAAMAIQeAJ8nD64qELE
                 rELMsEqIyG6cyG7U1HLY2HrY3HrhBKrlCK6pGM7lD LKtHM7pKNL5MNtiViNaon
                 +GqoNSyq9WzrNyyqtuzq+O0que/t+bIwubJw+vJw+vTz+zT z////////yH5BAE
                 KAB8ALAAAAAAMAAwAAAVJIMUMZEkylGKuwzgc0kPCcgl123NcHWYW Fs6Gp2mYB
                 IRgR7MIrAwVDifjWO2WwZzpxkxyfKVCpImMGAeIgQDgVLMHikmCRUpMQgA7 ''')
        )

        self.style.element_create("close", "image", "img_close",
               ("active", "pressed", "!disabled", "img_closepressed"),
               ("active", "alternate", "!disabled",
               "img_closeactive"), border=8, sticky='')

        self.style.layout("ClosetabNotebook", [("ClosetabNotebook.client",
                                     {"sticky": "nswe"})])
        self.style.layout("ClosetabNotebook.Tab", [
            ("ClosetabNotebook.tab",
              { "sticky": "nswe",
                "children": [
                    ("ClosetabNotebook.padding", {
                        "side": "top",
                        "sticky": "nswe",
                        "children": [
                            ("ClosetabNotebook.focus", {
                                "side": "top",
                                "sticky": "nswe",
                                "children": [
                                    ("ClosetabNotebook.label", {"side":
                                      "left", "sticky": ''}),
                                    ("ClosetabNotebook.close", {"side":
                                        "left", "sticky": ''}),]})]})]})])

        PNOTEBOOK = "ClosetabNotebook" 

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.PNotebook1 = ttk.Notebook(top)
        self.PNotebook1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.PNotebook1.configure(width=300)
        self.PNotebook1.configure(style=PNOTEBOOK)
        self.PNotebook1_t0 = Frame(self.PNotebook1)
        self.PNotebook1.add(self.PNotebook1_t0, padding=3)
        self.PNotebook1.tab(0, text="MEDIA",compound="none",underline="-1",)
        self.PNotebook1_t1 = Frame(self.PNotebook1)
        self.PNotebook1.add(self.PNotebook1_t1, padding=3)
        self.PNotebook1.tab(1, text="WORDS",compound="none",underline="-1",)

        self.frame_mediabuttons = ttk.Frame(self.PNotebook1_t0)
        self.frame_mediabuttons.place(relx=0.07, rely=0.21, relheight=0.35
                , relwidth=0.18)
        self.frame_mediabuttons.configure(relief=GROOVE)
        self.frame_mediabuttons.configure(borderwidth="2")
        self.frame_mediabuttons.configure(relief=GROOVE)
        self.frame_mediabuttons.configure(width=155)
        self.frame_mediabuttons.configure(takefocus="0")

        self.btn_DeleteMedia = Button(self.frame_mediabuttons)
        self.btn_DeleteMedia.place(relx=0.13, rely=0.6, height=66, width=104)
        self.btn_DeleteMedia.configure(activebackground="#d9d9d9")
        self.btn_DeleteMedia.configure(command=project_movie_slicer4_support.delete_movie)
        self.btn_DeleteMedia.configure(takefocus="0")
        self.btn_DeleteMedia.configure(text='''Delete''')

        self.btn_addmovie = Button(self.frame_mediabuttons)
        self.btn_addmovie.place(relx=0.13, rely=0.17, height=66, width=102)
        self.btn_addmovie.configure(activebackground="#d9d9d9")
        self.btn_addmovie.configure(command=project_movie_slicer4_support.add_media_2_db)
        self.btn_addmovie.configure(text='''ADD''')

        self.TFrame2 = ttk.Frame(self.PNotebook1_t0)
        self.TFrame2.place(relx=0.06, rely=0.8, relheight=0.16, relwidth=0.59)
        self.TFrame2.configure(relief=GROOVE)
        self.TFrame2.configure(borderwidth="2")
        self.TFrame2.configure(relief=GROOVE)
        self.TFrame2.configure(width=505)
        self.TFrame2.configure(takefocus="0")

        self.pNo38_t0_tFr40_tLa41 = ttk.Label(self.TFrame2)
        self.pNo38_t0_tFr40_tLa41.place(relx=0.04, rely=0.19, height=16
                , width=59)
        self.pNo38_t0_tFr40_tLa41.configure(background="#d9d9d9")
        self.pNo38_t0_tFr40_tLa41.configure(foreground="#000000")
        self.pNo38_t0_tFr40_tLa41.configure(font="TkDefaultFont")
        self.pNo38_t0_tFr40_tLa41.configure(relief=FLAT)
        self.pNo38_t0_tFr40_tLa41.configure(takefocus="0")
        self.pNo38_t0_tFr40_tLa41.configure(text='''media url''')

        self.label_suburl = ttk.Label(self.TFrame2)
        self.label_suburl.place(relx=0.04, rely=0.57, height=16, width=50)
        self.label_suburl.configure(background="#d9d9d9")
        self.label_suburl.configure(foreground="#000000")
        self.label_suburl.configure(font="TkDefaultFont")
        self.label_suburl.configure(relief=FLAT)
        self.label_suburl.configure(takefocus="0")
        self.label_suburl.configure(text='''subs url''')

        self.entry_media_url = Entry(self.TFrame2)
        self.entry_media_url.place(relx=0.2, rely=0.1,height=25, relwidth=0.41)
        self.entry_media_url.configure(background="white")
        self.entry_media_url.configure(font=font10)
        self.entry_media_url.configure(selectbackground="#c4c4c4")
        self.entry_media_url.configure(takefocus="0")
        self.entry_media_url.configure(textvariable=project_movie_slicer4_support.media_url_txt)

        self.pNo38_t0_tFr40_ent48 = Entry(self.TFrame2)
        self.pNo38_t0_tFr40_ent48.place(relx=0.2, rely=0.48, height=25
                , relwidth=0.41)
        self.pNo38_t0_tFr40_ent48.configure(background="white")
        self.pNo38_t0_tFr40_ent48.configure(font=font10)
        self.pNo38_t0_tFr40_ent48.configure(selectbackground="#c4c4c4")
        self.pNo38_t0_tFr40_ent48.configure(takefocus="0")
        self.pNo38_t0_tFr40_ent48.configure(textvariable=project_movie_slicer4_support.subs_url_txt)

        self.btn_browse_subs = Button(self.TFrame2)
        self.btn_browse_subs.place(relx=0.81, rely=0.57, height=26, width=69)
        self.btn_browse_subs.configure(activebackground="#d9d9d9")
        self.btn_browse_subs.configure(command=project_movie_slicer4_support.load_sub_file)
        self.btn_browse_subs.configure(takefocus="0")
        self.btn_browse_subs.configure(text='''Browse''')

        self.btn_browse_media = Button(self.TFrame2)
        self.btn_browse_media.place(relx=0.81, rely=0.19, height=26, width=69)
        self.btn_browse_media.configure(activebackground="#d9d9d9")
        self.btn_browse_media.configure(command=project_movie_slicer4_support.load_media_file)
        self.btn_browse_media.configure(takefocus="0")
        self.btn_browse_media.configure(text='''Browse''')

        self.Canvas1 = Canvas(self.PNotebook1_t0)
        self.Canvas1.place(relx=0.35, rely=0.09, relheight=0.56, relwidth=0.54)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(takefocus="0")
        self.Canvas1.configure(width=461)

        self.Frame1 = Frame(self.Canvas1)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=0.0, relwidth=0.0)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=125)

        self.TProgressbar1 = ttk.Progressbar(self.PNotebook1_t0)
        self.TProgressbar1.place(relx=0.67, rely=0.74, relwidth=0.31
                , relheight=0.0, height=19)
        self.TProgressbar1.configure(variable=project_movie_slicer4_support.progress_var)

        self.TCombobox1 = ttk.Combobox(self.PNotebook1_t0)
        self.TCombobox1.place(relx=0.47, rely=0.05, relheight=0.03
                , relwidth=0.21)
        self.TCombobox1.configure(textvariable=project_movie_slicer4_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Frame2 = Frame(self.PNotebook1_t0)
        self.Frame2.place(relx=0.67, rely=0.8, relheight=0.16, relwidth=0.3)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=255)

        self.lbl_time_progressed = Label(self.Frame2)
        self.lbl_time_progressed.place(relx=0.12, rely=0.1, height=18, width=196)

        self.lbl_time_progressed.configure(activebackground="#f9f9f9")
        self.lbl_time_progressed.configure(text='''Label''')
        self.lbl_time_progressed.configure(textvariable=project_movie_slicer4_support.time_progressed)

        self.lbl_progress_percent = Label(self.Frame2)
        self.lbl_progress_percent.place(relx=0.12, rely=0.38, height=18
                , width=196)
        self.lbl_progress_percent.configure(activebackground="#f9f9f9")
        self.lbl_progress_percent.configure(text='''Label''')
        self.lbl_progress_percent.configure(textvariable=project_movie_slicer4_support.progress_percent)

        self.lbl_completion_time = Label(self.Frame2)
        self.lbl_completion_time.place(relx=0.12, rely=0.69, height=18
                , width=196)
        self.lbl_completion_time.configure(activebackground="#f9f9f9")
        self.lbl_completion_time.configure(text='''Label''')
        self.lbl_completion_time.configure(textvariable=project_movie_slicer4_support.completion_time)

        self.frame_wordbuttons = Frame(self.PNotebook1_t1)
        self.frame_wordbuttons.place(relx=0.04, rely=0.39, relheight=0.44
                , relwidth=0.21)
        self.frame_wordbuttons.configure(relief=GROOVE)
        self.frame_wordbuttons.configure(borderwidth="2")
        self.frame_wordbuttons.configure(relief=GROOVE)
        self.frame_wordbuttons.configure(width=175)

        self.btn_generateword = Button(self.frame_wordbuttons)
        self.btn_generateword.place(relx=0.23, rely=0.1, height=26, width=81)
        self.btn_generateword.configure(activebackground="#d9d9d9")
        self.btn_generateword.configure(command=project_movie_slicer4_support.generate_vid_cmd)
        self.btn_generateword.configure(takefocus="0")
        self.btn_generateword.configure(text='''Generate''')

        self.Button4 = Button(self.frame_wordbuttons)
        self.Button4.place(relx=0.23, rely=0.34, height=26, width=85)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(takefocus="0")
        self.Button4.configure(text='''Download''')

        self.btn_delete = Button(self.frame_wordbuttons)
        self.btn_delete.place(relx=0.23, rely=0.61, height=26, width=64)
        self.btn_delete.configure(activebackground="#d9d9d9")
        self.btn_delete.configure(takefocus="0")
        self.btn_delete.configure(text='''Delete''')

        self.frame_searchword = Frame(self.PNotebook1_t1)
        self.frame_searchword.place(relx=0.02, rely=0.06, relheight=0.26
                , relwidth=0.28)
        self.frame_searchword.configure(relief=GROOVE)
        self.frame_searchword.configure(borderwidth="2")
        self.frame_searchword.configure(relief=GROOVE)
        self.frame_searchword.configure(width=235)

        self.pNo38_t1_fra56_ent57 = Entry(self.frame_searchword)
        self.pNo38_t1_fra56_ent57.place(relx=0.04, rely=0.23, height=25
                , relwidth=0.88)
        self.pNo38_t1_fra56_ent57.configure(background="white")
        self.pNo38_t1_fra56_ent57.configure(font=font10)
        self.pNo38_t1_fra56_ent57.configure(selectbackground="#c4c4c4")
        self.pNo38_t1_fra56_ent57.configure(takefocus="0")
        self.pNo38_t1_fra56_ent57.configure(textvariable=project_movie_slicer4_support.search_word_var)

        self.btn_searchword = Button(self.frame_searchword)
        self.btn_searchword.place(relx=0.3, rely=0.51, height=26, width=68)
        self.btn_searchword.configure(activebackground="#d9d9d9")
        self.btn_searchword.configure(command=project_movie_slicer4_support.btn_search_cmd)
        self.btn_searchword.configure(takefocus="0")
        self.btn_searchword.configure(text='''Search''')

        self.Listbox1 = Listbox(self.PNotebook1_t1)
        self.Listbox1.place(relx=0.34, rely=0.11, relheight=0.74, relwidth=0.6)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font=font10)
        self.Listbox1.configure(width=514)
        self.Listbox1.configure(listvariable=project_movie_slicer4_support.words_found_list)
        self.PNotebook1.bind('<Button-1>',project_movie_slicer4_support.button_press)
        self.PNotebook1.bind('<ButtonRelease-1>',project_movie_slicer4_support.button_release)
        self.PNotebook1.bind('<Motion>',project_movie_slicer4_support.mouse_over)






if __name__ == '__main__':
    vp_start_gui()



